In [2]:
import pandas as pd

C:\Users\Asus\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\Asus\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [3]:
df1 = pd.read_csv("../Data/Raw/01_fund_master.csv")

In [4]:
df1.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [5]:
df1.shape

(40, 15)

In [6]:
df1.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [7]:
df1.dtypes

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [8]:
df1.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [9]:
df1.duplicated().sum()

0

In [68]:
df1['fund_house'].unique()

<ArrowStringArray>
[         'SBI Mutual Fund',         'HDFC Mutual Fund',
      'ICICI Prudential MF',          'Nippon India MF',
        'Kotak Mahindra MF',         'Axis Mutual Fund',
 'Aditya Birla Sun Life MF',          'UTI Mutual Fund',
           'Mirae Asset MF',          'DSP Mutual Fund']
Length: 10, dtype: str

In [69]:
df1['sub_category'].unique()

<ArrowStringArray>
[      'Large Cap',       'Small Cap',            'Gilt',         'Mid Cap',
  'Short Duration',           'Value',          'Liquid',       'Index/ETF',
       'Flexi Cap',           'Index', 'Large & Mid Cap',            'ELSS']
Length: 12, dtype: str

In [70]:
df1['category'].unique()

<ArrowStringArray>
['Equity', 'Debt']
Length: 2, dtype: str

In [71]:
df1['risk_category'].unique()

<ArrowStringArray>
['Moderate', 'Very High', 'Low', 'High', 'Moderately High']
Length: 5, dtype: str

In [74]:
df1['amfi_code'].head(10)

0    119551
1    119552
2    119598
3    119599
4    119120
5    100016
6    125497
7    100033
8    125498
9    100025
Name: amfi_code, dtype: int64

In [73]:
df1['amfi_code'].nunique()

40

In [75]:
df1[["amfi_code", "scheme_name"]].head(10)

   amfi_code                                        scheme_name
0     119551          SBI Bluechip Fund - Regular Plan - Growth
1     119552           SBI Bluechip Fund - Direct Plan - Growth
2     119598         SBI Small Cap Fund - Regular Plan - Growth
3     119599          SBI Small Cap Fund - Direct Plan - Growth
4     119120       SBI Magnum Gilt Fund - Regular Plan - Growth
5     100016          HDFC Top 100 Fund - Regular Plan - Growth
6     125497           HDFC Top 100 Fund - Direct Plan - Growth
7     100033  HDFC Mid-Cap Opportunities Fund - Regular - Gr...
8     125498  HDFC Mid-Cap Opportunities Fund - Direct - Growth
9     100025       HDFC Short Term Debt Fund - Regular - Growth

In [76]:
df1["amfi_code"].duplicated().sum()

0

In [10]:
df2 = pd.read_csv("../Data/Raw/02_nav_history.csv")

In [11]:
df2.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [12]:
df2.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [13]:
df2.shape

(46000, 3)

In [14]:
df2.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [77]:
set(df1['amfi_code'])-set(df2['amfi_code'])

set()

In [15]:
df3 = pd.read_csv("../Data/Raw/03_aum_by_fund_house.csv")

In [16]:
df3.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [17]:
df3.shape

(90, 5)

In [18]:
df3.dtypes

date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [19]:
df3.duplicated().sum()

0

In [20]:
df3.isnull().sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [21]:
df4 = pd.read_csv("../Data/Raw/04_monthly_sip_inflows.csv")

In [22]:
df4.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [23]:
df4.shape

(48, 6)

In [24]:
df4.dtypes

month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [25]:
df4.isnull().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [26]:
df4.duplicated().sum()

0

In [27]:
df5 = pd.read_csv("../Data/Raw/05_category_inflows.csv")

In [28]:
df5.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [29]:
df5.shape

(144, 3)

In [30]:
df5.dtypes

month                   str
category                str
net_inflow_crore    float64
dtype: object

In [31]:
df5.isnull().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [32]:
df5.duplicated().sum()

0

In [33]:
df6 = pd.read_csv("../Data/Raw/06_industry_folio_count.csv")

In [34]:
df6.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [35]:
df6.shape

(21, 6)

In [36]:
df6.dtypes

month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

In [37]:
df6.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [38]:
df6.duplicated().sum()

0

In [39]:
df7 = pd.read_csv("../Data/Raw/07_scheme_performance.csv")

In [40]:
df7.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [41]:
df7.shape

(40, 19)

In [42]:
df7.dtypes

amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

In [43]:
df7.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [46]:
df7.duplicated().sum()

0

In [47]:
df8 = pd.read_csv("../Data/Raw/08_investor_transactions.csv")

In [48]:
df8.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [49]:
df8.shape

(32778, 13)

In [50]:
df8.dtypes

investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

In [51]:
df8.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [52]:
df8.duplicated().sum()

0

In [53]:
df9 = pd.read_csv("../Data/Raw/09_portfolio_holdings.csv")

In [54]:
df9.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [55]:
df9.shape

(322, 8)

In [56]:
df9.dtypes

amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

In [57]:
df9.isnull().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [58]:
df9.duplicated().sum()

0

In [59]:
df10 = pd.read_csv("../Data/Raw/10_benchmark_indices.csv")

In [60]:
df10.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [61]:
df10.shape

(8050, 3)

In [62]:
df10.dtypes

date               str
index_name         str
close_value    float64
dtype: object

In [63]:
df10.isnull().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [64]:
df10.duplicated().sum()

0

In [78]:
import requests 
url="https://api.mfapi.in/mf/125497"
response = requests.get(url)
response.status_code

200

In [80]:
data = response.json()
type(data)

dict

In [81]:
data.keys()

dict_keys(['meta', 'data', 'status'])

In [83]:
data['meta']

{'fund_house': 'SBI Mutual Fund',
 'scheme_type': 'Open Ended Schemes',
 'scheme_category': 'Equity Scheme - Small Cap Fund',
 'scheme_code': 125497,
 'scheme_name': 'SBI Small Cap Fund - Direct Plan - Growth',
 'isin_growth': 'INF200K01T51',
 'isin_div_reinvestment': None}

In [84]:
Nav_df = pd.DataFrame(data['data'])

In [85]:
Nav_df.head()

         date        nav
0  01-06-2026  192.31950
1  31-05-2026  193.68360
2  29-05-2026  193.68480
3  27-05-2026  195.05010
4  26-05-2026  194.22580

In [ ]:
Nav_df.to_csv("../Data/Raw/live_nav_125497.csv",index=False)

In [88]:
import requests
import pandas as pd

def Fetch_Nav(amfi_code):
    url = f"https://api.mfapi.in/mf/{amfi_code}"

    response = requests.get(url)
    data=response.json()
    Nav_Df = pd.DataFrame(data['data'])
    Nav_Df.to_csv(f"../Data/Raw/Nav_{amfi_code}.csv",index=False)

    print(f"Saved NAV data for {amfi_code}")

    return Nav_Df.head()

In [89]:
Fetch_Nav(119551)
Fetch_Nav(120503)
Fetch_Nav(118632)
Fetch_Nav(119092)
Fetch_Nav(120841)

Saved NAV data for 119551
Saved NAV data for 120503
Saved NAV data for 118632
Saved NAV data for 119092
Saved NAV data for 120841

         date        nav
0  01-06-2026  246.98140
1  29-05-2026  248.66730
2  27-05-2026  251.22730
3  26-05-2026  251.27020
4  25-05-2026  249.22660

In [90]:
df1[df1["amfi_code"] == 125497]

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
6,125497,HDFC Mutual Fund,HDFC Top 100 Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.92,1.0,500,1000,Rahul Baijal,Moderate,EC01

In [91]:
data["meta"]["scheme_code"]

125497

In [92]:
data["meta"]["scheme_name"]

'SBI Small Cap Fund - Direct Plan - Growth'

OBSERVATIONS---

-- Fund Master contains 40 unique amfi schemes.
-- Categories Present - Equity and Dept .
-- 12 different Sub Categories Found .
-- Risk Categories - 5 found(Low , Moderate , High , Moderately High , Very High ) .
-- All AMFI codes from fund_master exist in nav_history - no code is missing .
-- Live NAV data successfully fetched from mfapi and saved as live_nav_125497.CSV.
-- NAV history contains date and NAV values for each scheme.
-- API and master data mismatch observed for AMFI code 125497:
   - fund_master.csv → HDFC Top 100 Fund - Direct Plan - Growth
   - mfapi response → SBI Small Cap Fund - Direct Plan - Growth